from app.webapp.admin.admin import *
from app.webapp.admin.digitization import *
from app.webapp.admin.digitization_source import *
from app.webapp.admin.conservation_place import *
from app.webapp.admin.content import *
from app.webapp.admin.edition import *
from app.webapp.admin.language import *
from app.webapp.admin.person import *
from app.webapp.admin.place import *
from app.webapp.admin.role import *
from app.webapp.admin.series import *
from app.webapp.admin.tag import *
from app.webapp.admin.witness import *
from app.webapp.admin.work import *
from app.webapp.admin.treatment import *
