# syntax=docker/dockerfile:1
FROM node:23.11

# aiiinotate port
ARG PORT
ENV PORT=${PORT}

ENV http_proxy=http://195.221.193.15:3128
ENV https_proxy=http://195.221.193.15:3128
ENV no_proxy=localhost,127.0.0.1,.aikon_network
ENV HTTP_PROXY=http://195.221.193.15:3128
ENV HTTPS_PROXY=http://195.221.193.15:3128
ENV NO_PROXY=localhost,127.0.0.1,.aikon_network

RUN echo 'Acquire::http::Proxy "http://195.221.193.15:3128";' > /etc/apt/apt.conf.d/proxy.conf && \
    echo 'Acquire::https::Proxy "http://195.221.193.15:3128";' >> /etc/apt/apt.conf.d/proxy.conf && \
    echo 'Acquire::CompressionTypes::Order:: "gz";' > /etc/apt/apt.conf.d/99disable-compressors && \
    echo 'APT::Get::AllowUnauthenticated "true";' >> /etc/apt/apt.conf.d/99disable-compressors

# path to the .env file
ARG ENV_PATH
ENV ENV_PATH="$ENV_PATH"

# set up environment
ENV DIR=/aiiinotate
ENV TERM=linux
ENV NPM_BIN=/aiiinotate/node_modules/.bin
SHELL ["/bin/bash", "-c"]

# root of the app in the docker container
WORKDIR ${DIR}
# copy the docker .env in the docker container
COPY "$ENV_PATH" ${DIR}/.env
# for debug: install `iproute2` which provides CLI `ss` to monitor active ports
# for healthcheck: install CURL.
# NOTE: all the arguments are a temporary fix to avoid `Release file for http://deb.debian.org/debian-security/dists/bookworm-security/InRelease is not valid yet`
RUN apt-get -o Acquire::Check-Valid-Until=false -o Acquire::Check-Date=false update
RUN apt install curl iproute2 -y
# RUN apt update && apt install iproute2 -y
# create a npm package in $DIR to run aiiinotate from
RUN npm init -y
# install the app as an NPM library. we do a global install as it saves us from issues with `$PATH`.
RUN npm i aiiinotate@">=0.9.1"
#RUN npm i aiiinotate

# expose the used port
EXPOSE ${PORT}

# run the migrations and start the app.
# ./node_modules/.bin/aiiinotate is to be able to use the `aiiinotate` cli without doing a global install of `aiiinotate`
# NOTE migrations must be done in CMD: they need the mongo service to be running.
CMD ${NPM_BIN}/dotenvx run -f ${DIR}/.env -- ${NPM_BIN}/aiiinotate migrate apply && \
    ${NPM_BIN}/dotenvx run -f ${DIR}/.env -- ${NPM_BIN}/aiiinotate serve prod;
