# syntax=docker/dockerfile:1
FROM node:23.11

# mirador port
ARG PORT
ENV PORT=${PORT}

ENV http_proxy=http://195.221.193.15:3128
ENV https_proxy=http://195.221.193.15:3128
ENV no_proxy=localhost,127.0.0.1,.aikon_network
ENV HTTP_PROXY=http://195.221.193.15:3128
ENV HTTPS_PROXY=http://195.221.193.15:3128
ENV NO_PROXY=localhost,127.0.0.1,.aikon_network

RUN echo 'Acquire::http::Proxy "http://195.221.193.15:3128";' > /etc/apt/apt.conf.d/proxy.conf && \
    echo 'Acquire::https::Proxy "http://195.221.193.15:3128";' >> /etc/apt/apt.conf.d/proxy.conf && \
    echo 'Acquire::CompressionTypes::Order:: "gz";' > /etc/apt/apt.conf.d/99disable-compressors && \
    echo 'APT::Get::AllowUnauthenticated "true";' >> /etc/apt/apt.conf.d/99disable-compressors

# path to the .env file
ARG ENV_PATH
ENV ENV_PATH="$ENV_PATH"

# set up environment
ENV TERM=linux
ENV TZ=Europe/Paris
SHELL ["/bin/bash", "-c"]
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# root of the app
WORKDIR /mirador
# for debug: install `iproute2` which provides CLI `ss` to monitor active ports
# NOTE: all the arguments are a temporary fix to avoid `Release file for http://deb.debian.org/debian-security/dists/bookworm-security/InRelease is not valid yet`
RUN apt-get -o Acquire::Check-Valid-Until=false -o Acquire::Check-Date=false update
RUN apt install iproute2 -y
# copy the .env
COPY "$ENV_PATH" /mirador/.env
# copy the package.json.
# the cwd on the host server is defined by services.<service-name>.build.context
COPY ./annotations /mirador
COPY ./annotations/package.json /mirador/package.json
# install dependencies
RUN npm i;

RUN chmod +x /mirador/scripts/run_mirador_prod.sh

EXPOSE ${PORT}

CMD [ "bash", "/mirador/scripts/run_mirador_prod.sh", "/mirador/.env" ]
