# Generated by Django 4.0.4 on 2024-01-25 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "webapp",
            "0001_conservationplace_content_digitizationsource_edition_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="series",
            name="notes",
            field=models.TextField(
                blank=True,
                max_length=600,
                verbose_name="Éléments descriptifs du contenu",
            ),
        ),
    ]
