# Generated by Django 4.0.4 on 2024-01-26 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0003_alter_work_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="edition",
            name="name",
            field=models.CharField(
                help_text="Nom sans valeur historique, utile pour distinguer plusieurs éditions partageant date et lieu de publication",
                max_length=500,
                verbose_name="Titre",
            ),
        ),
    ]
