# Generated by Django 5.1.6 on 2025-03-13 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0012_digitization_json_digitization_source_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="documentset",
            options={
                "verbose_name": "Set de documents",
                "verbose_name_plural": "Set de documentss",
            },
        ),
        migrations.AddField(
            model_name="treatment",
            name="api_parameters",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="treatment",
            name="task_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("regions", "Extraction de régions d'images"),
                    ("similarity", "Calcul de score de similarité"),
                    ("vectorization", "Vectorisation"),
                ],
                max_length=50,
                null=True,
                verbose_name="Type de tâche",
            ),
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "picture",
                    models.ImageField(
                        blank=True, upload_to="picture/", verbose_name="Image"
                    ),
                ),
                (
                    "role",
                    models.CharField(blank=True, max_length=200, verbose_name="Rôle"),
                ),
                (
                    "affiliation",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Affiliation"
                    ),
                ),
                (
                    "presentation",
                    models.TextField(
                        blank=True, max_length=3000, verbose_name="Présentation"
                    ),
                ),
                (
                    "is_team",
                    models.BooleanField(
                        default=False,
                        verbose_name="Afficher le profil sur la page équipe",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Profil utilisateur",
                "verbose_name_plural": "Profil utilisateurs",
            },
        ),
    ]
