# Generated by Django 4.0.4 on 2024-08-07 07:25

import app.webapp.models.content
import app.webapp.models.digitization
import app.webapp.utils.iiif.validation
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions
import functools


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0014_documentset_json_documentset_selection_series_json_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="conservationplace",
            options={
                "verbose_name": "Conservation place",
                "verbose_name_plural": "Conservation places",
            },
        ),
        migrations.AlterModelOptions(
            name="content",
            options={"verbose_name": "Content", "verbose_name_plural": "Contents"},
        ),
        migrations.AlterModelOptions(
            name="digitization",
            options={
                "verbose_name": "Digitization",
                "verbose_name_plural": "Digitizations",
            },
        ),
        migrations.AlterModelOptions(
            name="digitizationsource",
            options={
                "verbose_name": "Digitization source",
                "verbose_name_plural": "Digitization sources",
            },
        ),
        migrations.AlterModelOptions(
            name="documentset",
            options={
                "verbose_name": "Document set",
                "verbose_name_plural": "Document sets",
            },
        ),
        migrations.AlterModelOptions(
            name="edition",
            options={"verbose_name": "Edition", "verbose_name_plural": "Editions"},
        ),
        migrations.AlterModelOptions(
            name="language",
            options={"verbose_name": "Language", "verbose_name_plural": "Languages"},
        ),
        migrations.AlterModelOptions(
            name="person",
            options={
                "verbose_name": "Historical actor",
                "verbose_name_plural": "Historical actors",
            },
        ),
        migrations.AlterModelOptions(
            name="place",
            options={"verbose_name": "Place", "verbose_name_plural": "Places"},
        ),
        migrations.AlterModelOptions(
            name="regionpair",
            options={
                "verbose_name": "Region pair",
                "verbose_name_plural": "Region pairs",
            },
        ),
        migrations.AlterModelOptions(
            name="regions",
            options={"verbose_name": "Regions", "verbose_name_plural": "Regions"},
        ),
        migrations.AlterModelOptions(
            name="role",
            options={"verbose_name": "Role", "verbose_name_plural": "Roles"},
        ),
        migrations.AlterModelOptions(
            name="series",
            options={"verbose_name": "Series", "verbose_name_plural": "Series"},
        ),
        migrations.AlterModelOptions(
            name="treatment",
            options={"verbose_name": "Treatment", "verbose_name_plural": "Treatments"},
        ),
        migrations.AlterModelOptions(
            name="witness",
            options={
                "ordering": ["-place"],
                "verbose_name": "Witness",
                "verbose_name_plural": "Witnesses",
            },
        ),
        migrations.AlterModelOptions(
            name="work",
            options={"verbose_name": "Work", "verbose_name_plural": "Works"},
        ),
        migrations.AddField(
            model_name="regions",
            name="json",
            field=models.JSONField(
                blank=True, null=True, verbose_name="JSON representation"
            ),
        ),
        migrations.AlterField(
            model_name="regionpair",
            name="regions_id_1",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="regionpair",
            name="regions_id_2",
            field=models.IntegerField(),
        ),
        migrations.AddIndex(
            model_name="regionpair",
            index=models.Index(
                fields=["regions_id_1", "img_1"], name="webapp_regi_regions_96cfbb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="regionpair",
            index=models.Index(
                fields=["regions_id_2", "img_2"], name="webapp_regi_regions_defc04_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="regionpair",
            index=models.Index(
                condition=models.Q(
                    ("regions_id_1", django.db.models.expressions.F("regions_id_2"))
                ),
                fields=["regions_id_1", "regions_id_2"],
                name="idx_same_regions",
            ),
        ),
        migrations.AddIndex(
            model_name="regionpair",
            index=models.Index(
                fields=["img_1", "regions_id_1", "regions_id_2"],
                name="webapp_regi_img_1_685841_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="regionpair",
            index=models.Index(
                fields=["img_2", "regions_id_1", "regions_id_2"],
                name="webapp_regi_img_2_c47c92_idx",
            ),
        ),
    ]
