# Generated by Django 5.1.6 on 2025-03-31 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0019_treatment_api_parameters_alter_treatment_task_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="regionpair",
            name="similarity_type",
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
