# Generated by Django 5.1.6 on 2025-05-16 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0021_regionpair_similarity_type_populate"),
    ]

    operations = [
        migrations.AddField(
            model_name="treatment",
            name="info",
            field=models.TextField(blank=True, null=True),
        ),
    ]
