# Generated by Django 5.2.2 on 2025-10-07 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0023_regionpair_propagation_delete"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Regions",
            new_name="RegionExtraction",
        ),
        migrations.AlterModelOptions(
            name="regionextraction",
            options={
                "verbose_name": "Region extraction",
                "verbose_name_plural": "Region extraction",
            },
        ),
    ]
