# Generated by Django 5.2.7 on 2025-11-27 15:40

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0023_regionpair_propagation_delete"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentset",
            name="users_id",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(),
                blank=True,
                default=list,
                null=True,
                size=None,
            ),
        ),
    ]
