# Generated by Django 5.1.6 on 2026-01-07 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0024_alter_regionpair_category_x"),
    ]

    operations = [
        migrations.CreateModel(
            name="SimilarityParameters",
            fields=[
                (
                    "hash",
                    models.CharField(max_length=8, primary_key=True, serialize=False),
                ),
                ("parameters", models.JSONField()),
            ],
        ),
        migrations.RemoveConstraint(
            model_name="regionpair",
            name="unique_img_pair",
        ),
        migrations.RemoveField(
            model_name="regionpair",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="regionpair",
            name="is_manual",
        ),
        migrations.RemoveField(
            model_name="regionpair",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="regionpair",
            name="similarity_hash",
            field=models.CharField(blank=True, default=None, max_length=8, null=True),
        ),
        migrations.AddConstraint(
            model_name="regionpair",
            constraint=models.UniqueConstraint(
                fields=("img_1", "img_2", "similarity_hash"), name="unique_img_pair"
            ),
        ),
    ]
