# Generated by Django 5.2.7 on 2025-12-11 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0024_documentset_users_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="documentset",
            old_name="users_id",
            new_name="shared_with",
        ),
    ]
