# Generated by Django 5.2.7 on 2026-01-12 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0024_alter_regionpair_category_x"),
        ("webapp", "0025_rename_users_id_documentset_shared_with"),
    ]

    operations = []
