# Generated by Django 5.2.7 on 2026-01-12 14:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0026_merge_20260112_1359"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="witness",
            name="shared_with",
            field=models.ManyToManyField(
                blank=True,
                related_name="shared_witnesses",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Shared with",
            ),
        ),
    ]
