# Generated by Django 5.1.6 on 2026-01-23 14:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0028_witness_shared_with"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="series",
            name="shared_with",
            field=models.ManyToManyField(
                blank=True,
                related_name="shared_series",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Partagé avec",
            ),
        ),
    ]
