# Generated by Django 5.2.7 on 2026-03-02 15:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0029_alter_series_shared_with"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="treatment",
            name="task_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("region_extraction", "Image regions extraction"),
                    ("similarity", "Compute similarity score"),
                    ("vectorization", "Vectorization"),
                ],
                max_length=50,
                null=True,
                verbose_name="Task type",
            ),
        ),
        migrations.CreateModel(
            name="RegionExtraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "json",
                    models.JSONField(
                        blank=True, null=True, verbose_name="JSON representation"
                    ),
                ),
                ("model", models.CharField(max_length=150)),
                ("is_validated", models.BooleanField(default=False)),
                (
                    "digitization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="region_extractions",
                        to="webapp.digitization",
                        verbose_name="Digitization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Region extraction",
                "verbose_name_plural": "Region extractions",
            },
        ),
        migrations.DeleteModel(
            name="Regions",
        ),
    ]
