# Generated by Django 5.2.7 on 2026-03-02 15:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0030_alter_treatment_task_type_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="series",
            name="shared_with",
            field=models.ManyToManyField(
                blank=True,
                related_name="shared_series",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Shared with",
            ),
        ),
        migrations.AlterField(
            model_name="witness",
            name="shared_with",
            field=models.ManyToManyField(
                blank=True,
                related_name="shared_witnesses",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Shared with",
            ),
        ),
    ]
