# Generated by Django 5.2.7 on 2026-03-02 15:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0032_remove_regionpair_webapp_regi_img_1_new_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="treatment",
            name="task_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("region_extraction", "Image regions extraction"),
                    ("similarity", "Compute similarity score"),
                    ("vectorization", "Vectorization"),
                ],
                max_length=50,
                null=True,
                verbose_name="Task type",
            ),
        ),
        migrations.RenameModel(
            old_name="Regions",
            new_name="RegionExtraction",
        ),
    ]
