# Generated by Django 5.2.13 on 2026-05-07 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0032_region"),
    ]

    operations = [
        migrations.AlterField(
            model_name="region",
            name="id",
            field=models.CharField(editable=False, primary_key=True, serialize=False),
        ),
    ]
