# Generated by Django 5.2.6 on 2026-02-16 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0032_add_pair_ordering_constraint"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="regionpair",
            name="webapp_regi_img_1_new_idx",
        ),
        migrations.RemoveIndex(
            model_name="regionpair",
            name="webapp_regi_img_2_new_idx",
        ),
    ]
