# Generated by Django 5.2.7 on 2026-04-08 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0033_alter_treatment_task_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "json",
                    models.JSONField(
                        blank=True, null=True, verbose_name="JSON representation"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, max_length=3000, verbose_name="Additional notes"
                    ),
                ),
                (
                    "region_extraction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="regions",
                        to="webapp.regionextraction",
                        verbose_name="Region extraction",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, to="webapp.tag", verbose_name="Tag"
                    ),
                ),
            ],
            options={
                "verbose_name": "Region",
                "verbose_name_plural": "Regions",
            },
        ),
    ]
