# Generated by Django 6.0.2 on 2026-09-17 13:08

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0033_region"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="regionextraction",
            options={
                "verbose_name": "Region extraction",
                "verbose_name_plural": "Region extractions",
            },
        ),
        migrations.AlterField(
            model_name="regionextraction",
            name="digitization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="region_extractions",
                to="webapp.digitization",
                verbose_name="Digitization",
            ),
        ),
        migrations.AlterField(
            model_name="series",
            name="shared_with",
            field=models.ManyToManyField(
                blank=True,
                related_name="shared_series",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Shared with",
            ),
        ),
        migrations.AlterField(
            model_name="treatment",
            name="task_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("region_extraction", "Image regions extraction"),
                    ("similarity", "Compute similarity score"),
                    ("vectorization", "Vectorization"),
                    ("import", "Import"),
                ],
                max_length=50,
                null=True,
                verbose_name="Task type",
            ),
        ),
        migrations.AlterField(
            model_name="witness",
            name="shared_with",
            field=models.ManyToManyField(
                blank=True,
                related_name="shared_witnesses",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Shared with",
            ),
        ),
        migrations.CreateModel(
            name="RegionSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "json",
                    models.JSONField(
                        blank=True, null=True, verbose_name="JSON representation"
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("is_public", models.BooleanField(default=False)),
                (
                    "region_ids",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(),
                        blank=True,
                        default=list,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "shared_with",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(),
                        blank=True,
                        default=list,
                        null=True,
                    ),
                ),
                (
                    "selection",
                    models.JSONField(
                        blank=True, null=True, verbose_name="JSON selection"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Region set",
                "verbose_name_plural": "Region sets",
            },
        ),
        migrations.AddField(
            model_name="treatment",
            name="region_set",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="treatments",
                to="webapp.regionset",
                verbose_name="Region set",
            ),
        ),
        migrations.DeleteModel(
            name="Region",
        ),
    ]
