# Generated by Django 6.0.2 on 2026-07-20 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0033_remove_regionpair_webapp_regi_img_1_new_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='task_type',
            field=models.CharField(blank=True, choices=[('region_extraction', 'Image regions extraction'), ('similarity', 'Compute similarity score'), ('vectorization', 'Vectorization'), ('import', 'Import')], max_length=50, null=True, verbose_name='Task type'),
        ),
        migrations.CreateModel(
            name='RegionExtraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json', models.JSONField(blank=True, null=True, verbose_name='JSON representation')),
                ('model', models.CharField(max_length=150)),
                ('is_validated', models.BooleanField(default=False)),
                ('digitization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='region_extractions', to='webapp.digitization', verbose_name='Digitization')),
            ],
            options={
                'verbose_name': 'Region extraction',
                'verbose_name_plural': 'Region extractions',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json', models.JSONField(blank=True, null=True, verbose_name='JSON representation')),
                ('notes', models.TextField(blank=True, max_length=3000, verbose_name='Additional notes')),
                ('tags', models.ManyToManyField(blank=True, to='webapp.tag', verbose_name='Tag')),
                ('region_extraction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regions', to='webapp.regionextraction', verbose_name='Region extraction')),
            ],
            options={
                'verbose_name': 'Region',
                'verbose_name_plural': 'Regions',
            },
        ),
        migrations.DeleteModel(
            name='Regions',
        ),
    ]
