# Generated by Django 6.0.2 on 2026-09-21 15:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0034_alter_regionextraction_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="regionset",
            name="region_ids",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=50),
                blank=True,
                default=list,
                null=True,
            ),
        ),
    ]
