version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn app.config.wsgi:application --bind 0.0.0.0:8001 --workers 4
    volumes:
      - ./app:/home/aikon/app
      - ./celery:/home/aikon/celery
      - ./cantaloupe:/home/aikon/cantaloupe
      - ./sas:/home/aikon/sas
    ports:
      - "8001:8001"
    depends_on:
      - db
      - redis
    environment:
      - POSTGRES_DB=your_db
      - POSTGRES_USER=your_user
      - POSTGRES_PASSWORD=your_password
    networks:
      - app_network
  db:
    image: postgres:13
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=your_db
      - POSTGRES_USER=your_user
      - POSTGRES_PASSWORD=your_password
    networks:
      - app_network
  redis:
    image: redis:6
    volumes:
      - redisdata:/data
    networks:
      - app_network
  celery:
    build:
      context: .
      dockerfile: Dockerfile
    command: ./start.sh
    volumes:
      - ./celery:/home/aikon/celery
    depends_on:
      - redis
      - db
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    networks:
      - app_network
  cantaloupe:
    image: openjdk:11-jdk
    build:
      context: ./cantaloupe
    command: ./start.sh
    ports:
      - "8182:8182"
    volumes:
      - ./cantaloupe:/home/aikon/cantaloupe
    networks:
      - app_network
  sas:
    image: openjdk:11-jdk
    build:
      context: ./sas
    command: ./start.sh
    volumes:
      - ./sas:/home/aikon/sas
    ports:
      - "8888:8888"
    networks:
      - app_network
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./app/staticfiles:/home/aikon/app/staticfiles
      - /media/datafiles:/data/mediafiles
    depends_on:
      - web
    networks:
      - app_network
volumes:
  pgdata:
  redisdata:

networks:
  app_network:
