services:
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        USERID: ${USERID}
        PORT: ${DJANGO_PORT}
    volumes:
      - ${DATA_FOLDER}:/data
      - ../app:/home/aikon/app
    env_file:
      - ../app/config/.env
      - ./.env
    ports:
      - "${DJANGO_PORT}:8000"
    depends_on:
      - db
      - redis
#      db:
#        condition: service_healthy
#      redis:
#        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/test/" ]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - app_network
    restart: unless-stopped

  db:
    image: postgres:13
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - ../app/config/.env
    networks:
      - app_network
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:6
    volumes:
      - redisdata:/data
    networks:
      - app_network
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

#  celery:
#    build:
#      context: ..
#      dockerfile: docker/Dockerfile
#      args:
#        USERID: ${USERID}
#        PORT: ${DJANGO_PORT}
#    command: /home/aikon/celery/start.sh
#    volumes:
#      - ../celery:/home/aikon/celery
#      - ../app:/home/aikon/app
#    depends_on:
#      - web
#      - redis
#      - db
#    env_file:
#      - ../app/config/.env
#      - ./.env
#    networks:
#      - app_network

  cantaloupe:
    build:
      context: ../cantaloupe
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - "${CANTALOUPE_PORT:-8182}:8182"
    volumes:
      - ../cantaloupe:/home/aikon/cantaloupe
      - ${DATA_FOLDER}:/data
    networks:
      - app_network
    user: root

  sas:
    build:
      context: ../sas
      dockerfile: Dockerfile
    volumes:
      - ../sas:/home/aikon/sas
    env_file:
      - ./.env
    ports:
      - "${SAS_PORT:-8888}:8888"
    networks:
      - app_network

  nginx:
    image: nginx:latest
    env_file:
      - ../app/config/.env
      - ./.env
    ports:
      - "${NGINX_PORT:-80}:80"
    environment:
      - PROD_URL=${PROD_URL:-localhost}
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ../app/staticfiles:/home/aikon/app/staticfiles:ro
      - ${DATA_FOLDER}:/data:ro
    depends_on:
      web:
        condition: service_healthy
      cantaloupe:
        condition: service_healthy
      sas:
        condition: service_healthy
    networks:
      - app_network
    restart: unless-stopped

volumes:
  pgdata:
  redisdata:

networks:
  app_network:
    driver: bridge
