# Generated by Django 4.0.4 on 2024-02-07 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "webapp",
            "0001_conservationplace_content_digitizationsource_edition_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="digitization",
            name="source",
            field=models.ForeignKey(
                blank=True,
                help_text="Exemple : Gallica.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="webapp.digitizationsource",
                verbose_name="Source de la numérisation",
            ),
        ),
    ]
