# Generated by Django 4.0.4 on 2024-01-26 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0002_alter_series_notes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="work",
            name="title",
            field=models.CharField(max_length=600, verbose_name="Titre"),
        ),
    ]
