# Generated by Django 4.0.4 on 2024-05-30 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("webapp", "0003_regionpair_alter_conservationplace_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="witness",
            name="series",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="webapp.series",
                verbose_name="Series",
            ),
        ),
        migrations.CreateModel(
            name="Treatment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "task_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("extraction", "extraction"),
                            ("similarity", "similarity"),
                            ("vectorization", "vectorization"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "treatment_type",
                    models.CharField(
                        blank=True,
                        choices=[("auto", "auto"), ("manual", "manual")],
                        default="auto",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True, default="created", max_length=50, null=True
                    ),
                ),
                (
                    "treated_object",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="treatments",
                        to="webapp.digitization",
                        verbose_name="Digitization",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Treatment",
                "verbose_name_plural": "Treatments",
            },
        ),
    ]
