# Generated by Django 4.0.4 on 2024-06-13 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0004_alter_witness_series_treatment"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Annotation",
            new_name="Regions",
        ),
        migrations.RenameField(
            model_name="regionpair",
            old_name="anno_ref_1",
            new_name="regions_ref_1",
        ),
        migrations.RenameField(
            model_name="regionpair",
            old_name="anno_ref_2",
            new_name="regions_ref_2",
        ),
        migrations.AlterField(
            model_name="treatment",
            name="task_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("regions", "regions"),
                    ("similarity", "similarity"),
                    ("vectorization", "vectorization"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
