# Generated by Django 4.0.4 on 2024-04-08 07:20

import app.webapp.utils.iiif.validation
from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("webapp", "0004_alter_edition_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="content",
            name="date_min",
            field=models.IntegerField(
                blank=True,
                help_text="Saisissez une année au format numérique. Exemple : '1401' à '1500' pour indiquer le 15<sup>ème</sup> siècle.",
                null=True,
                verbose_name="Date minimale",
            ),
        ),
        migrations.AlterField(
            model_name="digitization",
            name="manifest",
            field=models.URLField(
                blank=True,
                help_text="<div class='tooltip'>\n                        <i class='fa-solid fa-circle-info'></i>\n                        <span class='tooltiptext'>Un manifeste permet de décrire et de partager des numérisations avec leurs métadonnées selon la norme IIIF.</span>\n                    </div>\n                    E.g.: <a href='https://gallica.bnf.fr/iiif/ark:/12148/btv1b60004321/manifest.json' target='_blank'>\n                    https://gallica.bnf.fr/iiif/ark:/12148/btv1b60004321/manifest.json</a>",
                validators=[app.webapp.utils.iiif.validation.validate_manifest],
                verbose_name="manifest",
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pub", "éditeur/diffuseur"),
                    ("aut", "auteur"),
                    ("ill", "enlumineur"),
                    ("sel", "libraire"),
                    ("cop", "copiste"),
                    ("dra", "dessinateur"),
                    ("eng", "graveur"),
                    ("tra", "traducteur"),
                ],
                max_length=150,
                verbose_name="Rôle",
            ),
        ),
        migrations.AlterField(
            model_name="series",
            name="date_min",
            field=models.IntegerField(
                blank=True,
                help_text="Saisissez une année au format numérique. Exemple : '1401' à '1500' pour indiquer le 15<sup>ème</sup> siècle.",
                null=True,
                verbose_name="Date minimale",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="label",
            field=models.CharField(max_length=50, verbose_name="Label"),
        ),
        migrations.AlterField(
            model_name="witness",
            name="notes",
            field=models.TextField(
                blank=True, max_length=3000, verbose_name="Notes complémentaires"
            ),
        ),
        migrations.AlterField(
            model_name="work",
            name="date_min",
            field=models.IntegerField(
                blank=True,
                help_text="Saisissez une année au format numérique. Exemple : '1401' à '1500' pour indiquer le 15<sup>ème</sup> siècle.",
                null=True,
                verbose_name="Date minimale",
            ),
        ),
        migrations.CreateModel(
            name="RegionPair",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("img_1", models.CharField(max_length=150)),
                ("img_2", models.CharField(max_length=150)),
                ("anno_ref_1", models.CharField(max_length=150)),
                ("anno_ref_2", models.CharField(max_length=150)),
                (
                    "categories",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Paire de régions",
                "verbose_name_plural": "Paire de régionss",
            },
        ),
        migrations.AddConstraint(
            model_name="regionpair",
            constraint=models.UniqueConstraint(
                fields=("img_1", "img_2"), name="unique_img_pair"
            ),
        ),
    ]
