# Generated by Django 4.0.4 on 2024-04-12 01:46

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0005_alter_content_date_min_alter_digitization_manifest_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="regionpair",
            name="categories",
        ),
        migrations.RemoveField(
            model_name="regionpair",
            name="user",
        ),
        migrations.AddField(
            model_name="regionpair",
            name="category",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="regionpair",
            name="category_x",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(), default=list, size=None
            ),
        ),
    ]
