# Generated by Django 4.0.4 on 2024-05-07 16:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("webapp", "0006_remove_regionpair_categories_remove_regionpair_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="witness",
            name="series",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="webapp.series",
                verbose_name="Série",
            ),
        ),
        migrations.CreateModel(
            name="APITask",
            fields=[
                (
                    "experiment_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("task_type", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "status",
                    models.CharField(
                        blank=True, default="created", max_length=50, null=True
                    ),
                ),
                (
                    "digitization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="api_tasks",
                        to="webapp.digitization",
                        verbose_name="Numérisation",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Tâche api",
                "verbose_name_plural": "Tâche apis",
            },
        ),
    ]
