# Generated by Django 4.0.4 on 2024-08-05 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0009_documentset_regions_remove_annotation_digitization_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="documentset",
            options={
                "verbose_name": "Set de documents",
                "verbose_name_plural": "Paniers de documents",
            },
        ),
        migrations.AddField(
            model_name="documentset",
            name="json",
            field=models.JSONField(
                blank=True, null=True, verbose_name="JSON representation"
            ),
        ),
        migrations.AddField(
            model_name="documentset",
            name="selection",
            field=models.JSONField(
                blank=True, null=True, verbose_name="JSON selection"
            ),
        ),
        migrations.AddField(
            model_name="series",
            name="json",
            field=models.JSONField(
                blank=True, null=True, verbose_name="JSON representation"
            ),
        ),
        migrations.AddField(
            model_name="treatment",
            name="json",
            field=models.JSONField(
                blank=True, null=True, verbose_name="JSON representation"
            ),
        ),
        migrations.AddField(
            model_name="witness",
            name="json",
            field=models.JSONField(
                blank=True, null=True, verbose_name="JSON representation"
            ),
        ),
        migrations.AddField(
            model_name="work",
            name="json",
            field=models.JSONField(
                blank=True, null=True, verbose_name="JSON representation"
            ),
        ),
        migrations.AlterField(
            model_name="treatment",
            name="task_type",
            field=models.CharField(
                blank=True,
                choices=[("regions", "regions"), ("similarity", "similarity")],
                max_length=50,
                null=True,
            ),
        ),
    ]
