# Generated by Django 5.1.1 on 2024-10-17 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0016_alter_conservationplace_city_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="digitization",
            name="json",
            field=models.JSONField(
                blank=True, null=True, verbose_name="JSON representation"
            ),
        ),
        migrations.AlterField(
            model_name="treatment",
            name="task_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("regions", "Image regions extraction"),
                    ("vectorization", "Vectorization"),
                    ("similarity", "Compute similarity score"),
                ],
                max_length=50,
                null=True,
                verbose_name="Task type",
            ),
        ),
    ]
