# Generated by Django 5.1.3 on 2024-11-20 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0016_alter_conservationplace_city_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="treatment",
            name="task_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("regions", "Image regions extraction"),
                    ("similarity", "Compute similarity score"),
                ],
                max_length=50,
                null=True,
                verbose_name="Task type",
            ),
        ),
    ]
