# Generated by Django 5.1.5 on 2025-01-30 08:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0017_digitization_json_alter_treatment_task_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "picture",
                    models.ImageField(
                        blank=True, upload_to="picture/", verbose_name="Picture"
                    ),
                ),
                (
                    "role",
                    models.CharField(blank=True, max_length=200, verbose_name="Role"),
                ),
                (
                    "affiliation",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Affiliation"
                    ),
                ),
                (
                    "presentation",
                    models.TextField(
                        blank=True, max_length=3000, verbose_name="Presentation"
                    ),
                ),
                (
                    "is_team",
                    models.BooleanField(
                        default=False, verbose_name="Display profile on team page"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User profile",
                "verbose_name_plural": "User profiles",
            },
        ),
    ]
