# Generated by Django 5.1.3 on 2025-01-10 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0017_alter_treatment_task_type"),
        ("webapp", "0017_digitization_json_alter_treatment_task_type"),
    ]

    operations = []
