# Generated by Django 5.1.3 on 2025-02-03 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0018_merge_20250110_0912"),
    ]

    operations = [
        migrations.AddField(
            model_name="treatment",
            name="api_parameters",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
