# Generated by Django 4.0.4 on 2023-03-01 10:51

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import functools
import vhsapp.utils.functions
import vhsapp.utils.iiif


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, unique=True, verbose_name="Nom"),
                ),
            ],
            options={
                "verbose_name": "Auteur",
                "verbose_name_plural": "Auteurs",
            },
        ),
        migrations.CreateModel(
            name="DigitizedVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source", models.CharField(max_length=150, unique=True)),
            ],
            options={
                "verbose_name": "Source de la version numérisée",
                "verbose_name_plural": "Sources des versions numérisées",
            },
        ),
        migrations.CreateModel(
            name="Manuscript",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "manifest_final",
                    models.BooleanField(
                        default=False,
                        help_text="<i style='color:#efb80b' class='fa-solid fa-triangle-exclamation'></i> ATTENTION : la version en cours de vérification ne peut plus être modifiée.",
                        verbose_name="Valider les annotations",
                    ),
                ),
                ("slug", models.SlugField(max_length=600)),
                (
                    "conservation_place",
                    models.CharField(
                        max_length=150, verbose_name="Lieu de conservation"
                    ),
                ),
                (
                    "reference_number",
                    models.CharField(max_length=150, verbose_name="Cote"),
                ),
                (
                    "date_century",
                    models.CharField(
                        choices=[
                            ("XIXe", "XIXe"),
                            ("XVIIIe", "XVIIIe"),
                            ("XVIIe", "XVIIe"),
                            ("XVIe", "XVIe"),
                            ("XVe", "XVe"),
                            ("XIVe", "XIVe"),
                            ("XIIIe", "XIIIe"),
                            ("XIIe", "XIIe"),
                            ("XIe", "XIe"),
                            ("Xe", "Xe"),
                            ("IXe", "IXe"),
                            ("VIIIe", "VIIIe"),
                            ("VIIe", "VIIe"),
                            ("VIe", "VIe"),
                            ("Ve", "Ve"),
                            ("IVe", "IVe"),
                            ("IIIe", "IIIe"),
                            ("IIe", "IIe"),
                            ("Ier", "Ier"),
                        ],
                        max_length=150,
                        verbose_name="Date (siècle)",
                    ),
                ),
                (
                    "date_free",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Date (champ libre)"
                    ),
                ),
                (
                    "sheets",
                    models.CharField(max_length=150, verbose_name="Feuillet(s)"),
                ),
                (
                    "origin_place",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Lieu d'origine"
                    ),
                ),
                ("remarks", models.TextField(blank=True, verbose_name="Remarques")),
                (
                    "copyists",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="copiste(s)"
                    ),
                ),
                (
                    "miniaturists",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="miniaturiste(s)"
                    ),
                ),
                (
                    "pinakes_link",
                    models.URLField(
                        blank=True,
                        verbose_name="Lien vers Pinakes (mss grecs) ou Medium-IRHT (mss latins)",
                    ),
                ),
                (
                    "published",
                    models.BooleanField(
                        default=False,
                        help_text="Les informations seront accessibles aux autres utilisateurs de la base.",
                        verbose_name="ATTENTION : rendre accessible publiquement",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "author",
                    models.ForeignKey(
                        help_text="<ul><li>Indiquez [Anonyme] si auteur non identifié.</li><li>Si nom auteur non trouvé, merci de chercher directement dans <a href='https://data.bnf.fr/' target='_blank'>Data BnF</a>.</li></ul>",
                        max_length=200,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="vhsapp.author",
                        verbose_name="Auteur",
                    ),
                ),
                (
                    "digitized_version",
                    models.ForeignKey(
                        blank=True,
                        help_text="Exemples : Gallica, Photos personnelles [Stavros Lazaris], Biblioteca Apostolica Vaticana.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="vhsapp.digitizedversion",
                        verbose_name="Source de la version numérisée",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Manuscrit",
                "verbose_name_plural": "Manuscrits",
                "ordering": ["-conservation_place"],
            },
        ),
        migrations.CreateModel(
            name="Printed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=600)),
                ("place", models.CharField(max_length=150, verbose_name="Lieu")),
                ("date", models.CharField(max_length=150)),
                (
                    "publishers_booksellers",
                    models.CharField(max_length=150, verbose_name="Éditeurs/libraires"),
                ),
                (
                    "description",
                    models.TextField(verbose_name="Description de l'oeuvre"),
                ),
                (
                    "descriptive_elements",
                    models.TextField(
                        blank=True, verbose_name="Éléments descriptifs du contenu"
                    ),
                ),
                (
                    "illustrators",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Dessinateur(s)"
                    ),
                ),
                (
                    "engravers",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Graveur(s)"
                    ),
                ),
                (
                    "published",
                    models.BooleanField(
                        default=False,
                        help_text="Les informations seront accessibles aux autres utilisateurs de la base.",
                        verbose_name="ATTENTION : rendre accessible publiquement",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "author",
                    models.ForeignKey(
                        help_text="<ul><li>Indiquez [Anonyme] si auteur non identifié.</li><li>Si nom auteur non trouvé, merci de chercher directement dans <a href='https://data.bnf.fr/' target='_blank'>Data BnF</a>.</li></ul>",
                        max_length=200,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="vhsapp.author",
                        verbose_name="Auteurs et/ou Éditeurs scientifiques",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Imprimé",
                "verbose_name_plural": "Imprimés",
                "ordering": ["-place"],
            },
        ),
        migrations.CreateModel(
            name="Work",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=600, unique=True, verbose_name="Titre"),
                ),
            ],
            options={
                "verbose_name": "Titre",
                "verbose_name_plural": "Titre",
            },
        ),
        migrations.CreateModel(
            name="Volume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "manifest_final",
                    models.BooleanField(
                        default=False,
                        help_text="<i style='color:#efb80b' class='fa-solid fa-triangle-exclamation'></i> ATTENTION : la version en cours de vérification ne peut plus être modifiée.",
                        verbose_name="Valider les annotations",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=600, verbose_name="Titre du volume"),
                ),
                ("slug", models.SlugField(max_length=600)),
                (
                    "number_identifier",
                    models.CharField(
                        max_length=150,
                        verbose_name="Numéro ou élément d'identification du volume",
                    ),
                ),
                (
                    "place",
                    models.CharField(
                        help_text="Si différent de l'ensemble.",
                        max_length=150,
                        verbose_name="Lieu",
                    ),
                ),
                ("date", models.CharField(max_length=150)),
                (
                    "publishers_booksellers",
                    models.CharField(max_length=150, verbose_name="Éditeurs/libraires"),
                ),
                (
                    "comment",
                    models.TextField(blank=True, verbose_name="Commentaire éventuel"),
                ),
                (
                    "other_copies",
                    models.TextField(blank=True, verbose_name="Autre(s) exemplaire(s)"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "digitized_version",
                    models.ForeignKey(
                        blank=True,
                        help_text="Exemple : Gallica.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="vhsapp.digitizedversion",
                        verbose_name="Source de la version numérisée",
                    ),
                ),
                (
                    "printed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vhsapp.printed",
                        verbose_name="Imprimé",
                    ),
                ),
            ],
            options={
                "verbose_name": "Volume",
                "verbose_name_plural": "Volumes",
            },
        ),
        migrations.AddField(
            model_name="printed",
            name="work",
            field=models.ForeignKey(
                max_length=600,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="vhsapp.work",
                verbose_name="Titre de l'oeuvre",
            ),
        ),
        migrations.CreateModel(
            name="PdfVolume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pdf",
                    models.FileField(
                        upload_to=functools.partial(
                            vhsapp.utils.functions.rename_file,
                            *(),
                            **{"path": "volumes/pdf/"}
                        ),
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["pdf"]
                            )
                        ],
                        verbose_name="PDF",
                    ),
                ),
                (
                    "volume",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="vhsapp.volume"
                    ),
                ),
            ],
            options={
                "verbose_name": "PDF File",
                "verbose_name_plural": "PDF Files",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PdfManuscript",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pdf",
                    models.FileField(
                        upload_to=functools.partial(
                            vhsapp.utils.functions.rename_file,
                            *(),
                            **{"path": "manuscripts/pdf/"}
                        ),
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["pdf"]
                            )
                        ],
                        verbose_name="PDF",
                    ),
                ),
                (
                    "manuscript",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vhsapp.manuscript",
                    ),
                ),
            ],
            options={
                "verbose_name": "PDF File",
                "verbose_name_plural": "PDF Files",
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="manuscript",
            name="work",
            field=models.ForeignKey(
                help_text="Titre de l'oeuvre ou des oeuvres (même approximatif).",
                max_length=600,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="vhsapp.work",
                verbose_name="Titre de l'oeuvre",
            ),
        ),
        migrations.CreateModel(
            name="ManifestVolume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "manifest",
                    models.URLField(
                        help_text="<div class='tooltip'>\n                 <i class='fa-solid fa-circle-info' title='Manifest'></i>\n                 <span class='tooltiptext'>A IIIF manifest is the package that contains all the information related\n                 to a particular digital object, including the image itself as well as the metadata.</span>\n             </div>\n             E.g.: <a href='https://gallica.bnf.fr/iiif/ark:/12148/btv1b60004321/manifest.json' target='_blank'>\n             https://gallica.bnf.fr/iiif/ark:/12148/btv1b60004321/manifest.json</a>",
                        validators=[vhsapp.utils.iiif.validate_manifest],
                        verbose_name="manifest",
                    ),
                ),
                (
                    "volume",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="vhsapp.volume"
                    ),
                ),
            ],
            options={
                "verbose_name": "IIIF manifest",
                "verbose_name_plural": "IIIF manifests",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ManifestManuscript",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "manifest",
                    models.URLField(
                        help_text="<div class='tooltip'>\n                 <i class='fa-solid fa-circle-info' title='Manifest'></i>\n                 <span class='tooltiptext'>A IIIF manifest is the package that contains all the information related\n                 to a particular digital object, including the image itself as well as the metadata.</span>\n             </div>\n             E.g.: <a href='https://gallica.bnf.fr/iiif/ark:/12148/btv1b60004321/manifest.json' target='_blank'>\n             https://gallica.bnf.fr/iiif/ark:/12148/btv1b60004321/manifest.json</a>",
                        validators=[vhsapp.utils.iiif.validate_manifest],
                        verbose_name="manifest",
                    ),
                ),
                (
                    "manuscript",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vhsapp.manuscript",
                    ),
                ),
            ],
            options={
                "verbose_name": "IIIF manifest",
                "verbose_name_plural": "IIIF manifests",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ImageVolume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Envoyez des images jusqu'à 2 Go.",
                        upload_to=functools.partial(
                            vhsapp.utils.functions.rename_file, *(), **{"path": "img/"}
                        ),
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jpg", "jpeg", "png", "tif"]
                            )
                        ],
                        verbose_name="Image",
                    ),
                ),
                (
                    "volume",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="vhsapp.volume"
                    ),
                ),
            ],
            options={
                "verbose_name": "Image file",
                "verbose_name_plural": "Images files",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ImageManuscript",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Envoyez des images jusqu'à 2 Go.",
                        upload_to=functools.partial(
                            vhsapp.utils.functions.rename_file, *(), **{"path": "img/"}
                        ),
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jpg", "jpeg", "png", "tif"]
                            )
                        ],
                        verbose_name="Image",
                    ),
                ),
                (
                    "manuscript",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vhsapp.manuscript",
                    ),
                ),
            ],
            options={
                "verbose_name": "Image file",
                "verbose_name_plural": "Images files",
                "abstract": False,
            },
        ),
    ]
