# Generated by Django 4.0.4 on 2023-02-04 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vhsapp', '0002_alter_manuscript_reference_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manuscript',
            options={'ordering': ['-conservation_place'], 'verbose_name': 'Manuscrit', 'verbose_name_plural': 'Manuscrits'},
        ),
        migrations.RenameField(
            model_name='manuscript',
            old_name='place_conservation',
            new_name='conservation_place',
        ),
        migrations.RenameField(
            model_name='manuscript',
            old_name='place_origin',
            new_name='origin_place',
        ),
    ]
