# Generated by Django 4.0.4 on 2023-02-04 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vhsapp', '0003_alter_manuscript_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='printed',
            options={'ordering': ['-place'], 'verbose_name': 'Imprimé', 'verbose_name_plural': 'Imprimés'},
        ),
        migrations.RenameField(
            model_name='printed',
            old_name='elements_descriptifs',
            new_name='descriptive_elements',
        ),
        migrations.RenameField(
            model_name='printed',
            old_name='graveurs',
            new_name='engravers',
        ),
        migrations.RenameField(
            model_name='printed',
            old_name='dessinateurs',
            new_name='illustrators',
        ),
        migrations.RenameField(
            model_name='printed',
            old_name='lieu',
            new_name='place',
        ),
        migrations.RenameField(
            model_name='printed',
            old_name='editeurs',
            new_name='publishers_booksellers',
        ),
        migrations.RenameField(
            model_name='volume',
            old_name='commentaire_eventuel',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='volume',
            old_name='numero',
            new_name='number_identifier',
        ),
        migrations.RenameField(
            model_name='volume',
            old_name='autres_exemplaires',
            new_name='other_copies',
        ),
        migrations.RenameField(
            model_name='volume',
            old_name='lieu',
            new_name='place',
        ),
        migrations.RenameField(
            model_name='volume',
            old_name='editeurs',
            new_name='publishers_booksellers',
        ),
        migrations.RenameField(
            model_name='volume',
            old_name='titre',
            new_name='title',
        ),
    ]
