# Generated by Django 4.0.4 on 2023-02-04 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vhsapp', '0004_alter_printed_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printed',
            name='place',
            field=models.CharField(max_length=150, verbose_name='Lieu'),
        ),
        migrations.AlterField(
            model_name='volume',
            name='place',
            field=models.CharField(help_text="Si différent de l'ensemble.", max_length=150, verbose_name='Lieu'),
        ),
    ]
