# Generated by Django 4.0.4 on 2023-02-04 22:05

from django.db import migrations, models
import django.db.models.deletion
import vhsapp.utils.functions


class Migration(migrations.Migration):

    dependencies = [
        ('vhsapp', '0005_alter_printed_place_alter_volume_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manifestmanuscript',
            name='manifest',
            field=models.URLField(help_text='<div class="tooltip"><i class="fa-solid fa-circle-info" title="Manifest"></i><span class="tooltiptext">A IIIF manifest is the package that contains all the information related to a particular digital object, including the image itself as well as the metadata.</span></div>Exemple : <a href="https://gallica.bnf.fr/iiif/ark:/12148/btv1b60004321/manifest.json" target="_blank">https://gallica.bnf.fr/iiif/ark:/12148/btv1b60004321/manifest.json</a>', validators=[vhsapp.utils.functions.validate_gallica_manifest_url], verbose_name='Manifeste'),
        ),
        migrations.AlterField(
            model_name='manifestvolume',
            name='manifest',
            field=models.URLField(help_text='<div class="tooltip"><i class="fa-solid fa-circle-info" title="Manifest"></i><span class="tooltiptext">A IIIF manifest is the package that contains all the information related to a particular digital object, including the image itself as well as the metadata.</span></div>Exemple : <a href="https://gallica.bnf.fr/iiif/ark:/12148/btv1b60004321/manifest.json" target="_blank">https://gallica.bnf.fr/iiif/ark:/12148/btv1b60004321/manifest.json</a>', validators=[vhsapp.utils.functions.validate_gallica_manifest_url], verbose_name='Manifeste'),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='digitized_version',
            field=models.ForeignKey(blank=True, help_text='Exemples : Gallica, Photos personnelles [Stavros Lazaris], Biblioteca Apostolica Vaticana.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='vhsapp.digitizedversion', verbose_name='Source de la version numérisée'),
        ),
    ]
