# Generated by Django 4.0.4 on 2023-02-23 09:28

from django.db import migrations, models
import django.db.models.deletion
import vhsapp.utils.iiif


class Migration(migrations.Migration):

    dependencies = [
        ("vhsapp", "0006_alter_manifestmanuscript_manifest_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="imagemanuscript",
            options={
                "verbose_name": "Image file",
                "verbose_name_plural": "Images files",
            },
        ),
        migrations.AlterModelOptions(
            name="imagevolume",
            options={
                "verbose_name": "Image file",
                "verbose_name_plural": "Images files",
            },
        ),
        migrations.AlterModelOptions(
            name="manifestmanuscript",
            options={
                "verbose_name": "IIIF manifest",
                "verbose_name_plural": "IIIF manifests",
            },
        ),
        migrations.AlterModelOptions(
            name="manifestvolume",
            options={
                "verbose_name": "IIIF manifest",
                "verbose_name_plural": "IIIF manifests",
            },
        ),
        migrations.AlterModelOptions(
            name="pdfmanuscript",
            options={"verbose_name": "PDF File", "verbose_name_plural": "PDF Files"},
        ),
        migrations.AlterModelOptions(
            name="pdfvolume",
            options={"verbose_name": "PDF File", "verbose_name_plural": "PDF Files"},
        ),
        migrations.AlterField(
            model_name="manifestmanuscript",
            name="manifest",
            field=models.URLField(
                help_text="<div class='tooltip'>\n                 <i class='fa-solid fa-circle-info' title='Manifest'></i>\n                 <span class='tooltiptext'>A IIIF manifest is the package that contains all the information related\n                 to a particular digital object, including the image itself as well as the metadata.</span>\n             </div>\n             E.g.: <a href='https://gallica.bnf.fr/iiif/ark:/12148/btv1b60004321/manifest.json' target='_blank'>\n             https://gallica.bnf.fr/iiif/ark:/12148/btv1b60004321/manifest.json</a>",
                validators=[vhsapp.utils.iiif.validate_manifest],
                verbose_name="Manifest",
            ),
        ),
        migrations.AlterField(
            model_name="manifestvolume",
            name="manifest",
            field=models.URLField(
                help_text="<div class='tooltip'>\n                 <i class='fa-solid fa-circle-info' title='Manifest'></i>\n                 <span class='tooltiptext'>A IIIF manifest is the package that contains all the information related\n                 to a particular digital object, including the image itself as well as the metadata.</span>\n             </div>\n             E.g.: <a href='https://gallica.bnf.fr/iiif/ark:/12148/btv1b60004321/manifest.json' target='_blank'>\n             https://gallica.bnf.fr/iiif/ark:/12148/btv1b60004321/manifest.json</a>",
                validators=[vhsapp.utils.iiif.validate_manifest],
                verbose_name="Manifest",
            ),
        ),
        migrations.AlterField(
            model_name="manuscript",
            name="author",
            field=models.ForeignKey(
                help_text="<ul><li>Indiquez [Anonyme] si auteur non identifié.</li><li>Si nom auteur non trouvé, merci de chercher directement dans <a href='https://data.bnf.fr/' target='_blank'>Data BnF</a>.</li></ul>",
                max_length=200,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="vhsapp.author",
                verbose_name="Auteur",
            ),
        ),
        migrations.AlterField(
            model_name="manuscript",
            name="manifest_final",
            field=models.BooleanField(
                default=False,
                help_text="<i style='color:#efb80b' class='fa-solid fa-triangle-exclamation'></i> ATTENTION : la version en cours de vérification ne peut plus être modifiée.",
                verbose_name="Valider les annotations",
            ),
        ),
        migrations.AlterField(
            model_name="printed",
            name="author",
            field=models.ForeignKey(
                help_text="<ul><li>Indiquez [Anonyme] si auteur non identifié.</li><li>Si nom auteur non trouvé, merci de chercher directement dans <a href='https://data.bnf.fr/' target='_blank'>Data BnF</a>.</li></ul>",
                max_length=200,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="vhsapp.author",
                verbose_name="Auteurs et/ou Éditeurs scientifiques",
            ),
        ),
        migrations.AlterField(
            model_name="volume",
            name="manifest_final",
            field=models.BooleanField(
                default=False,
                help_text="<i style='color:#efb80b' class='fa-solid fa-triangle-exclamation'></i> ATTENTION : la version en cours de vérification ne peut plus être modifiée.",
                verbose_name="Valider les annotations",
            ),
        ),
    ]
